/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppShell {
    }
    interface RButton {
        /**
          * The button color (Ionic color)
         */
        "color"?: string;
        /**
          * If true, the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * If true, the button takes full width
         */
        "expand"?: 'full' | 'block';
        /**
          * Button fill style
         */
        "fill"?: 'clear' | 'outline' | 'solid' | 'default';
        /**
          * Icon name (Ionic icon name)
         */
        "icon"?: string;
        /**
          * If true, shows only the icon (icon-only button)
          * @default false
         */
        "iconOnly": boolean;
        /**
          * Icon position
         */
        "iconPosition"?: 'start' | 'end';
        /**
          * Button shape
         */
        "shape"?: 'round';
        /**
          * The button size
         */
        "size"?: 'small' | 'default' | 'large';
        /**
          * The button type (button, submit, reset)
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
    }
    interface RInput {
        /**
          * The input autocomplete attribute
         */
        "autocomplete"?: string;
        /**
          * If true, clears the input on edit
         */
        "clearOnEdit"?: boolean;
        /**
          * The input color (Ionic color)
         */
        "color"?: string;
        /**
          * If true, the input is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * If true, the input has error state
          * @default false
         */
        "error": boolean;
        /**
          * Error message to display
         */
        "errorText"?: string;
        /**
          * The input fill style
         */
        "fill"?: 'outline' | 'solid';
        /**
          * Helper text to display
         */
        "helperText"?: string;
        /**
          * The input label
         */
        "label"?: string;
        /**
          * Maximum length of the input
         */
        "maxlength"?: number;
        /**
          * Minimum length of the input
         */
        "minlength"?: number;
        /**
          * The input name
         */
        "name"?: string;
        /**
          * Pattern for validation
         */
        "pattern"?: string;
        /**
          * The input placeholder
         */
        "placeholder"?: string;
        /**
          * If true, the input is readonly
          * @default false
         */
        "readonly": boolean;
        /**
          * If true, the input is required
          * @default false
         */
        "required": boolean;
        /**
          * The input shape
         */
        "shape"?: 'round';
        /**
          * If true, shows password toggle button (only for password type)
          * @default true
         */
        "showPasswordToggle": boolean;
        /**
          * The input type (text, password, email, number, tel, url, search, etc.)
          * @default 'text'
         */
        "type": string;
        /**
          * The input value
         */
        "value"?: string;
    }
}
export interface RButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRButtonElement;
}
export interface RInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRInputElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppShellElement extends Components.AppShell, HTMLStencilElement {
    }
    var HTMLAppShellElement: {
        prototype: HTMLAppShellElement;
        new (): HTMLAppShellElement;
    };
    interface HTMLRButtonElementEventMap {
        "rClick": MouseEvent;
    }
    interface HTMLRButtonElement extends Components.RButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRButtonElementEventMap>(type: K, listener: (this: HTMLRButtonElement, ev: RButtonCustomEvent<HTMLRButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRButtonElementEventMap>(type: K, listener: (this: HTMLRButtonElement, ev: RButtonCustomEvent<HTMLRButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRButtonElement: {
        prototype: HTMLRButtonElement;
        new (): HTMLRButtonElement;
    };
    interface HTMLRInputElementEventMap {
        "rInput": CustomEvent;
        "rFocus": FocusEvent;
        "rBlur": FocusEvent;
    }
    interface HTMLRInputElement extends Components.RInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRInputElementEventMap>(type: K, listener: (this: HTMLRInputElement, ev: RInputCustomEvent<HTMLRInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRInputElementEventMap>(type: K, listener: (this: HTMLRInputElement, ev: RInputCustomEvent<HTMLRInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRInputElement: {
        prototype: HTMLRInputElement;
        new (): HTMLRInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-shell": HTMLAppShellElement;
        "r-button": HTMLRButtonElement;
        "r-input": HTMLRInputElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppShell {
    }
    interface RButton {
        /**
          * The button color (Ionic color)
         */
        "color"?: string;
        /**
          * If true, the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * If true, the button takes full width
         */
        "expand"?: 'full' | 'block';
        /**
          * Button fill style
         */
        "fill"?: 'clear' | 'outline' | 'solid' | 'default';
        /**
          * Icon name (Ionic icon name)
         */
        "icon"?: string;
        /**
          * If true, shows only the icon (icon-only button)
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Icon position
         */
        "iconPosition"?: 'start' | 'end';
        /**
          * Emitted when the button is clicked
         */
        "onRClick"?: (event: RButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button shape
         */
        "shape"?: 'round';
        /**
          * The button size
         */
        "size"?: 'small' | 'default' | 'large';
        /**
          * The button type (button, submit, reset)
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface RInput {
        /**
          * The input autocomplete attribute
         */
        "autocomplete"?: string;
        /**
          * If true, clears the input on edit
         */
        "clearOnEdit"?: boolean;
        /**
          * The input color (Ionic color)
         */
        "color"?: string;
        /**
          * If true, the input is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * If true, the input has error state
          * @default false
         */
        "error"?: boolean;
        /**
          * Error message to display
         */
        "errorText"?: string;
        /**
          * The input fill style
         */
        "fill"?: 'outline' | 'solid';
        /**
          * Helper text to display
         */
        "helperText"?: string;
        /**
          * The input label
         */
        "label"?: string;
        /**
          * Maximum length of the input
         */
        "maxlength"?: number;
        /**
          * Minimum length of the input
         */
        "minlength"?: number;
        /**
          * The input name
         */
        "name"?: string;
        /**
          * Emitted when the input is blurred
         */
        "onRBlur"?: (event: RInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input is focused
         */
        "onRFocus"?: (event: RInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the input value changes
         */
        "onRInput"?: (event: RInputCustomEvent<CustomEvent>) => void;
        /**
          * Pattern for validation
         */
        "pattern"?: string;
        /**
          * The input placeholder
         */
        "placeholder"?: string;
        /**
          * If true, the input is readonly
          * @default false
         */
        "readonly"?: boolean;
        /**
          * If true, the input is required
          * @default false
         */
        "required"?: boolean;
        /**
          * The input shape
         */
        "shape"?: 'round';
        /**
          * If true, shows password toggle button (only for password type)
          * @default true
         */
        "showPasswordToggle"?: boolean;
        /**
          * The input type (text, password, email, number, tel, url, search, etc.)
          * @default 'text'
         */
        "type"?: string;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-shell": AppShell;
        "r-button": RButton;
        "r-input": RInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-shell": LocalJSX.AppShell & JSXBase.HTMLAttributes<HTMLAppShellElement>;
            "r-button": LocalJSX.RButton & JSXBase.HTMLAttributes<HTMLRButtonElement>;
            "r-input": LocalJSX.RInput & JSXBase.HTMLAttributes<HTMLRInputElement>;
        }
    }
}
